### ISSUE TITLE
Inconsistent behaviour of the reset button on show xaml dialog

### ISSUE THREAD

**Issue by Bia10** [kikipoulet/SukiUI#138]
Currently the reset button does all sort of things inconsistently.

##  Leads to a sharing of state before reset to other same/similiar controlls/elements
![image](https://github.com/kikipoulet/SukiUI/assets/2548763/7f019371-bf8a-4061-81bb-f564cfd0a790)
![image](https://github.com/kikipoulet/SukiUI/assets/2548763/7cec4251-1c59-4b25-9718-e7f85d2d78d3)

## The controll dissapers entirely
![image](https://github.com/kikipoulet/SukiUI/assets/2548763/a9d816ff-d408-4660-a51e-c9fb1e576f41)
![image](https://github.com/kikipoulet/SukiUI/assets/2548763/b61cbc89-9115-4766-bfbd-8c2f208a032a)
![image](https://github.com/kikipoulet/SukiUI/assets/2548763/6d4b5cc6-a1e6-463c-b559-6bb581544656)

## Rarely crash simply occours

i have added a serilog sink to program.cs and this is the output...

```
2024-02-19 08:32:57.155 +01:00 [FTL] Oops something went wrong...
System.Xml.XmlException: xmlns declarations are only allowed on the root element to preserve memory Line 4, position 76. Line 3, position 76.
   at ShowMeTheXaml.AvaloniaRuntimeXamlLoaderHelper.ContentControlWrapperParse(String content, String namespaces)
   at ShowMeTheXaml.AvaloniaRuntimeXamlLoaderHelper.Parse(String content, String namespaces)
   at ShowMeTheXaml.AvaloniaRuntimeXamlLoaderHelper.Parse(String content, Dictionary`2 namespaces)
   at ShowMeTheXaml.XamlDisplay.Reset()
   at ShowMeTheXaml.XamlDisplayPopupBehavior.ResetButtonOnClick(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.PopupImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at SukiUI.Demo.Program.Main(String[] args) in C:\Users\Bia\source\repos\SukiUI\SukiUI.Demo\Program.cs:line 22
```

**Comment by sirdoombox** [comment]
This is largely bugs with `ShowMeTheXaml.Avalonia` and aren't really something we're in a position to fix, nor do we really need to.

The first issue you mentioned with sharing state is just a quirk of how I styled that particular page and is a simple fix though.

Honestly I think the best solution overall though is to make the xaml display readonly, as we now have the playground page whcih is better for trialing things out so just having the ability to quickly copy-paste the XAML is all that's necessary.
