### ISSUE TITLE
ubuntu 22.04 report Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.

### ISSUE THREAD

**Issue by eccsatan** [kikipoulet/SukiUI#145]
~/SukiUI/SukiUI.Demo/bin/Debug/net8.0$ dotnet SukiUI.Demo.dll

Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.AppBuilder.<>c__DisplayClass62_0.<ConfigureFonts>b__0(AppBuilder appBuilder)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at SukiUI.Demo.Program.Main(String[] args) in /home/ubuntu-2204/SukiUI/SukiUI.Demo/Program.cs:line 13

**Comment by kikipoulet** [comment]
Feel like it's more an Avalonia issue than SukiUI.

https://github.com/AvaloniaUI/Avalonia/issues/4427

I tried on Ubuntu to reproduce the bug and it didn't appeared, so I suppose you're up to read all these issues to find a workaround for you, sadly
