### ISSUE TITLE
Dialog not show on browser (WASM)

### ISSUE THREAD

**Issue by kinosang** [kikipoulet/SukiUI#168]
**Describe the bug**
seems dialog requires a `Window` control. any chance to use it without `suki:SukiWindow`?

**To Reproduce**
try use dialog in wasm project, it does not show.

**Expected behavior**

**Screenshots**

**Environment**
- OS Browser (WASM) / .Net 8.0
- Avalonia-Version 11.1.0-beta1
- SukiUI 6.0.0-beta4

**Additional context**
```
Uncaught    at System.Collections.Generic.Dictionary`2[[Avalonia.Controls.Window, Avalonia.Controls, Version=11.1.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b],[SukiUI.Controls.SukiHost, SukiUI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].FindValue(Window key)
   at System.Collections.Generic.Dictionary`2[[Avalonia.Controls.Window, Avalonia.Controls, Version=11.1.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b],[SukiUI.Controls.SukiHost, SukiUI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].TryGetValue(Window key, SukiHost& value)
   at SukiUI.Controls.SukiHost.ShowDialog(Window window, Object content, Boolean showCardBehind, Boolean allowBackgroundClose)
   at SukiUI.Controls.SukiHost.ShowDialog(Object content, Boolean showCardBehind, Boolean allowBackgroundClose)
   ...
Error: Value cannot be null. (Parameter 'key')
```

**Comment by kikipoulet** [comment]
Sure, you just have to put a <SukiHost> englobing your app, in your mainview for example, and you will be able to use dialogs and toasts.

Does it runs okay in browser ? I would be curious to have a screenshot :)

**Comment by kinosang** [comment]
@kikipoulet I've tried to copy & modify the `SukiHost`, `SukiToast` and `SukiToastPool`, change all `Window` types to `IRenderRoot`, and put modified `Host` in my `MainView`, it just works.

**Comment by kikipoulet** [comment]
super 👍
