### ISSUE TITLE
Using LiveCharts2 results in crash

### ISSUE THREAD

**Issue by pmichale** [kikipoulet/SukiUI#188]
**Describe the bug**
Since 6.0.0-beta5 trying to display a chart using LiveCharts2 results in a crash. Tested with Avalonia 11.1.0-beta2 **without** SukiUI to confirm that it's not caused by Avalonia itself. Previous version of SukiUI works fine.

**Stack trace:**
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'CropRect' from assembly 'SkiaSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'.
   at LiveChartsCore.SkiaSharpView.Painting.ImageFilters.DropShadow..ctor
   at LiveChartsCore.SkiaSharpView.SKCharts.SKDefaultTooltip..ctor()
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart.InitializeCore()
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart..ctor()
   at SukiTest.Pages.ChartView.!XamlIlPopulate(IServiceProvider, ChartView) in C:\Users\pmichale\Projects\github\SukiTest\SukiTest\Pages/ChartPage/ChartView.axaml:line 16
   at SukiTest.Pages.ChartView.!XamlIlPopulateTrampoline(ChartView)
   at SukiTest.Pages.ChartView.InitializeComponent(Boolean loadXaml) in C:\Users\pmichale\Projects\github\SukiTest\SukiTest\Avalonia.Generators\Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator\SukiTest.Pages.ChartView.g.cs:line 22
   at SukiTest.Pages.ChartView..ctor() in C:\Users\pmichale\Projects\github\SukiTest\SukiTest\Pages\ChartPage\ChartView.axaml.cs:line 11
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at SukiTest.ViewLocator.Build(Object data) in C:\Users\pmichale\Projects\github\SukiTest\SukiTest\ViewLocator.cs:line 26
   at Avalonia.Controls.Presenters.ContentPresenter.CreateChild(Object content, Control oldChild, IDataTemplate template)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content)
   at Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.Presenters.ContentPresenter.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaise(ValueStore owner, IValueEntry value, BindingPriority priority)
   at Avalonia.PropertyStore.ValueStore.ReevaluateEffectiveValue(AvaloniaProperty property, EffectiveValue current, IValueEntry changedValueEntry, Boolean ignoreLocalValue)
   at Avalonia.PropertyStore.ValueStore.Avalonia.Data.Core.IBindingExpressionSink.OnChanged(UntypedBindingExpressionBase instance, Boolean hasValueChanged, Boolean hasErrorChanged, Object value, BindingError error)
   at Avalonia.Data.Core.UntypedBindingExpressionBase.PublishValue(Object value, BindingError error)
   at Avalonia.Data.TemplateBinding.PublishValue()
   at Avalonia.Data.TemplateBinding.OnTemplatedParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetLocalValueAndRaise(ValueStore owner, StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at SukiUI.Controls.SukiTransitioningContentControl.set_SecondBuffer(Object value)
   at SukiUI.Controls.SukiTransitioningContentControl.PushContent(Object content)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at SukiTest.Program.Main(String[] args) in C:\Users\pmichale\Projects\github\SukiTest\SukiTest\Program.cs:line 13
```

**To Reproduce**
Use LiveCharts2 to plot a chart and launch the app. The crash occurs when navigating to a page that displays a chart, or immediately upon startup if the chart is set to display on the first page. See attached example.

**Expected behavior**
Anticipating that it functions as it did in prior versions.

**Environment**
- Windows 10 22H2, macOS Ventura 13.6
- Avalonia 11.1.0-beta2, SukiUI 6.0.0-beta5, LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-rc2

**Example**
[SukiTest.zip](https://github.com/kikipoulet/SukiUI/files/15307492/SukiTest.zip)

**Comment by kikipoulet** [comment]
This is because the last LIveCharts2 version use "older" skiasharp version 2.88.8 and Avalonia use skiasharp 3.0.0 since 11.1

So basically, you must wait for livecharts2 update (last package is 6 months old) to use it with avalonia last version. In the meantime, you can use 6.0.0-beta4 with avalonia 11.0.5 that will be using the same skaisharp version than last livecharts2 package.

**Comment by pmichale** [comment]
Thanks for the response. The only thing I don't get is why does it work fine with the newest Avalonia 11.1.0-beta2 until I introduce SukiUI into the mix. Any ideas on why that is?

**Comment by kikipoulet** [comment]
You're correct, this is not Avalonia which requires skiasharp 3.0.0, but us 🥸

Since SukiUI beta5

![image](https://github.com/kikipoulet/SukiUI/assets/19242427/e2545247-bbea-47c1-adc4-ee94a547fa99)

If there are no obvious reason I will downgrade the dependency to 2.88.8 as Avalonia in next beta.

**Comment by pmichale** [comment]
Perfect, thank you!
