### ISSUE TITLE
run fail

### ISSUE THREAD

**Issue by blackbutton** [kikipoulet/SukiUI#22]
Avalonia version: 11.0.0-preview6
Error:
System.MissingMethodException: Method not found: 'Void Avalonia.Controls.Primitives.FlyoutBase.set_Placement(Avalonia.Controls.FlyoutPlacementMode)'.
   at CompiledAvaloniaXaml.!AvaloniaResources.XamlClosure_175.Build(IServiceProvider)
   at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.<>c__DisplayClass1_0`1.<DeferredTransformationFactoryV2>b__0(IServiceProvider sp) in /_/src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs:line 37
   at Avalonia.Controls.ResourceDictionary.TryGetValue(Object key, Object& value) in /_/src/Avalonia.Base/Controls/ResourceDictionary.cs:line 244
   at Avalonia.Controls.ResourceDictionary.TryGetResource(Object key, ThemeVariant theme, Object& value) in /_/src/Avalonia.Base/Controls/ResourceDictionary.cs:line 189
   at Avalonia.Styling.Styles.TryGetResource(Object key, ThemeVariant theme, Object& value) in /_/src/Avalonia.Base/Styling/Styles.cs:line 120
   at Avalonia.Markup.Xaml.MarkupExtensions.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs:line 55
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Theme/TextBoxStyles.xaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Theme/TextBoxStyles.xaml(IServiceProvider)
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Theme/Index.xaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Theme/Index.xaml(IServiceProvider)
   at SukiUITest.App.!XamlIlPopulate(IServiceProvider, App) in D:\code-chance\DotNetCoreStudy\SukiUITest\SukiUITest\SukiUITest\App.axaml:line 13
   at SukiUITest.App.!XamlIlPopulateTrampoline(App)

**Comment by kikipoulet** [comment]
Last SukiUI package is based on preview5 right now.
Preview6 has some breaking changes so that's normal in a way
