### ISSUE TITLE
Avalonia 11 RC issue

### ISSUE THREAD

**Issue by curvedspace** [kikipoulet/SukiUI#38]
Hello, I am getting the following error with SukiUI 4.8 after upgrading to the Avalonia 11 RC packages.

![image](https://github.com/kikipoulet/SukiUI/assets/3098311/c5b8025d-63e2-48d4-9fe5-f3d071cee989)

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Avalonia.Styling.StyleBase.Add(Avalonia.Styling.ISetter)'.
  Source=SukiUI
  StackTrace:
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Theme/ComboBoxStyles.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Theme/Index.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Theme/Index.xaml(IServiceProvider )
   at Homesteadrr.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Users\shayn\source\repos\homesteadrr\Homesteadrr\App.axaml:line 12
   at Homesteadrr.App.!XamlIlPopulateTrampoline(App )
   at Homesteadrr.App.Initialize() in C:\Users\shayn\source\repos\homesteadrr\Homesteadrr\App.axaml.cs:line 14
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Homesteadrr.Program.Main(String[] args) in C:\Users\shayn\source\repos\homesteadrr\Homesteadrr\Program.cs:line 18

**Comment by curvedspace** [comment]
Just fyi, I saw someone on the Avalonia Telegram group had a similar issue and they think they will need to wait for an update to the Material Icons nuget package.

**Comment by kikipoulet** [comment]
Yep we had these kind of changes a lot with previews, SukiUI 4.8 is for preview8 so it's normal

Anyway I will update to RC in few days

**Comment by kikipoulet** [comment]
SukiUI 4.9 with avalonia RC is available

**Comment by sn4k3** [comment]
I get similar issue with 11.1-RC1 + SukiUI 6.0.0-beta7 but not with Avalonia 11.1-beta2

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<System.Object> Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlEagerParentStackProvider.get_DirectParents()'.
   at SukiUI.SukiTheme.!XamlIlPopulate(IServiceProvider, SukiTheme)
   at SukiUI.SukiTheme.!XamlIlPopulateTrampoline(SukiTheme)
   at SukiUI.SukiTheme..ctor()
   at App.!XamlIlPopulate(IServiceProvider, App) in App.axaml:line 12
   at App.!XamlIlPopulateTrampoline(App)
   at App.Initialize() in App.axaml.cs:line 15
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Desktop.Program.Main(String[] args) in Desktop\Program.cs:line 54
```

**Comment by handbros** [comment]
@sn4k3

It seems like a conflict between XAMLs compiled by 11.0 and ^11.1-RC1.
In the latest version(CI-66), the problem is not occurred.
* See a reference : https://github.com/AvaloniaUI/Avalonia/pull/16028

**Comment by chenhw** [comment]
@handbros I get the  similar issue with 11.1+ SukiUI 6.0.0-beta7

**Comment by AuroraZiling** [comment]
SukiUI 6.0.0-beta7 is outdated, wait for update
